### ISSUE TITLE
GatsbyJSでcontentfulを使用する方法を調査

### ISSUE THREAD

**Issue by 2no553** [froide-sub-ninomiya/kinshai#6]
- [ ] 現在のmasterからcontentfulを追加できるか確認する

- [次世代HeadlessCMS「contentful」事始め \- Qiita](https://qiita.com/daikiojm/items/3fbde3c88a7d0a053675)
- [ブログをGatsbyJS \+ Contentful \+ Netlifyで作り直したので今日はGatsby記念日 \- blog\.unresolved\.xyz](https://blog.unresolved.xyz/getting-started-gatsby-js-with-contentful-on-netlify/)
- [GatsbyJS and Contentful in five minutes](https://www.contentful.com/r/knowledgebase/gatsbyjs-and-contentful-in-five-minutes/)

**Comment by froide-sub-ninomiya** [comment]
使用方法まで確認。

### メリット
- コンテンツ（画像・文章）などの管理を開発側から切り離せる
- 仮にgatsbyjsからnuxtjsに変えたとしても言語やFWに関わらずコンテンツの移行が簡単
- 記事更新や編集のタイミングでnetlifyでコンテンツのビルドだけを走らせることができるから、ソースコードは変更せずに（gitでdiffやコンフリを出さずに）、表示されるコンテンツだけを更新できる。

### デメリット
- 慣れてる人がいないこと
- 料金プランが使用用途にどれだけ耐えられるかは要検討。

[Contentful: Content Infrastructure for Digital Teams](https://www.contentful.com/)
[Contentfulの料金と使い方を整理しつつ、Nuxt.jsと組み合わせてブログを作る - Qiita](https://qiita.com/noplan1989/items/466db319ec485ebc7db8)
[【入門】Nuxt.js + Contentful + Netlify で始める、JAMstack な CMS 構築 - Qiita](https://qiita.com/isihigameKoudai/items/3e45ade7c438176a4cc9)
